const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      "error-lighter": "var(--color-error-lighter)",
      "error-light": "var(--color-error-light)",
      error: "var(--color-error)",
      "error-dark": "var(--color-error-dark)",
      "success-lighter": "var(--color-success-lighter)",
      "success-light": "var(--color-success-light)",
      success: "var(--color-success)",
      "success-dark": "var(--color-success-dark)",
      "warning-lighter": "var(--color-warning-lighter)",
      "warning-light": "var(--color-warning-light)",
      warning: "var(--color-warning)",
      "warning-dark": "var(--color-warning-dark)",
      "violet-lighter": "var(--color-violet-lighter)",
      "violet-light": "var(--color-violet-light)",
      violet: "var(--color-violet)",
      "violet-dark": "var(--color-violet-dark)",
      "cyan-lighter": "var(--color-cyan-lighter)",
      "cyan-light": "var(--color-cyan-light)",
      cyan: "var(--color-cyan)",
      "cyan-dark": "var(--color-cyan-dark)",
      "highlight-purple": "var(--color-highlight-purple)",
      "highlight-magenta": "var(--color-highlight-magenta)",
      "highlight-pink": "var(--color-highlight-pink)",
      "highlight-yellow": "var(--color-highlight-yellow)",
      background: "var(--color-background)",
      "accent-1": "var(--color-accent-1)",
      "accent-2": "var(--color-accent-2)",
      "accent-3": "var(--color-accent-3)",
      "accent-4": "var(--color-accent-4)",
      "accent-5": "var(--color-accent-5)",
      "accent-6": "var(--color-accent-6)",
      "accent-7": "var(--color-accent-7)",
      "accent-8": "var(--color-accent-8)",
      foreground: "var(--color-foreground)",
      "highlight-background": "var(--color-cyan)",
      "highlight-foreground": "var(--color-foreground)",
    },
    extend: {
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
