import * as config from "@/lib/config";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import Link from "next/link";
import Script from "next/script";
import "./globals.css";
import { ThemeToggle } from "./theme-toggle";

const interSans = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script id="theme-preference">
        {`const theme = localStorage.getItem('theme');
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        if (theme === 'dark' || (!theme && prefersDark)) {
          document.documentElement.classList.add('dark');
        }`}
      </Script>
      <body
        className={`${interSans.variable} ${robotoMono.variable} antialiased h-full text-zinc-950 dark:text-white dark:bg-zinc-900 flex flex-col px-4 mx-auto max-w-prose scroll-smooth font-sans`}
      >
        <nav className="flex items-center justify-between pt-2 pb-6 md:pt-3 md:pb-8">
          <Link className="p-2 -ml-2 rounded-md md:text-lg" href="/">
            <b>{config.title}</b>
          </Link>
          <div className="relative flex items-center gap-1 font-mono text-sm md:gap-2">
            <ThemeToggle />
            <ul className="flex items-center gap-1">
              <li>
                <Link
                  className="p-2 rounded-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  href="/about"
                >
                  About
                </Link>
              </li>
              <li>
                <a
                  className="flex items-center gap-1 p-2 -mr-2 rounded-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  href={`https://bsky.app/profile/${config.bluesky}`}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="18"
                    height="18"
                    viewBox="0 0 600 530"
                  >
                    <path
                      d="m135.72 44.03c66.496 49.921 138.02 151.14 164.28 205.46 26.262-54.316 97.782-155.54 164.28-205.46 47.98-36.021 125.72-63.892 125.72 24.795 0 17.712-10.155 148.79-16.111 170.07-20.703 73.984-96.144 92.854-163.25 81.433 117.3 19.964 147.14 86.092 82.697 152.22-122.39 125.59-175.91-31.511-189.63-71.766-2.514-7.3797-3.6904-10.832-3.7077-7.8964-0.0174-2.9357-1.1937 0.51669-3.7077 7.8964-13.714 40.255-67.233 197.36-189.63 71.766-64.444-66.128-34.605-132.26 82.697-152.22-67.108 11.421-142.55-7.4491-163.25-81.433-5.9562-21.282-16.111-152.36-16.111-170.07 0-88.687 77.742-60.816 125.72-24.795z"
                      fill="currentColor"
                    />
                  </svg>
                  <span>Follow</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>
        <main className="grow">{children}</main>
        <footer className="flex justify-between pt-8 pb-4 font-mono text-sm text-zinc-400">
          <span>
            <span>{config.title}</span>{" "}
            <a
              className="underline underline-offset-2 hover:text-zinc-500 dark:hover:text-zinc-300"
              href={`https://bsky.app/profile/${config.bluesky}`}
            >
              @{config.bluesky}
            </a>
          </span>
          <a
            className="hover:text-zinc-500 dark:hover:text-zinc-300"
            href="https://github.com/sebsojeda/sebastianojeda.com"
          >
            Source
          </a>
        </footer>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
